apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: front-end-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: agammourya/front-end_project
        ports:
        - containerPort: 80
