version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tomato-food-app

    ports:
      - "2932:80"

    restart: unless-stopped

    networks:
      - tomato-network

networks:
  tomato-network:
    driver: bridge