apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: front-end-app
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30808

